### ISSUE TITLE
Which VR/AR Headset should I buy?

### ISSUE THREAD

**Issue by YQGong** [ILLIXR/ILLIXR#166]
Hi, I noticed that this project supports Monado runtime, and I want to run some openXR apps based on ILLIXR. But after I run `./runner.sh configs/monado.yaml`, the error message was `No non-desktop output available`.
Did this error caused by there is no VR headset found?

After that, I read the doc of monado and find out the hardware they support. But I wondered whether this project supports the same hardware as monado? Could you please recommend us a VR/AR headset which is the most suitable for research based on ILLIXR? By the way,  Could you please provide the recommended configuration of the host computer?

Thank you very much!

**Comment by Zee2** [comment]
Hi,

Right now, ILLIXR hijacks the display from Monado. This means that it doesn't use the typical direct-mode display that works with most consumer VR headsets that are usable for Monado.

Thus, right now ILLIXR is only for research purposes on traditional flat-screen displays. 

Soon, we will be migrating away from our hijacked-display "hack", and we'll be directly using Monado's display system. Therefore, as long as you have the proper tracking cameras (ZED Mini, or Intel Realsense, or whatever ILLIXR supports in the future), you may be able to use ILLIXR with a real headset, given that the lens/optical calibration parameters are known.

**Comment by Zee2** [comment]
Reopening for discussion of your other issues with the runner.

**Comment by YQGong** [comment]
hers is the message:

```
appo@appo:~/ILLIXR$ ./runner.sh configs/monado.yaml 
make: Entering directory '/home/appo/ILLIXR/runtime'
make: Entering directory '/home/appo/ILLIXR/ground_truth_slam'
make: Entering directory '/home/appo/ILLIXR/offline_imu_cam'
make: Entering directory '/home/appo/ILLIXR/open_vins'
make: Entering directory '/home/appo/ILLIXR/pose_prediction'
make: Entering directory '/home/appo/ILLIXR/timewarp_gl'
make: Entering directory '/home/appo/ILLIXR/audio_pipeline'
make: 'plugin.opt.so' is up to date.
make: Leaving directory '/home/appo/ILLIXR/offline_imu_cam'
make: 'plugin.opt.so' is up to date.
make: Leaving directory '/home/appo/ILLIXR/audio_pipeline'
make: 'plugin.opt.so' is up to date.
make: Leaving directory '/home/appo/ILLIXR/ground_truth_slam'
-- Could NOT find OpenHMD (missing: OPENHMD_INCLUDE_DIR OPENHMD_LIBRARY) 
make: 'plugin.opt.so' is up to date.
make: Leaving directory '/home/appo/ILLIXR/runtime'
make: 'plugin.opt.so' is up to date.
make: Leaving directory '/home/appo/ILLIXR/pose_prediction'
make -C build/Release "-j3" && \
rm -f plugin.opt.so && \
ln -s build/Release/ov_msckf/libslam2.so plugin.opt.so && \
true
make[1]: Entering directory '/home/appo/ILLIXR/open_vins'
make[1]: warning: -j3 forced in submake: resetting jobserver mode.
-- Configuring done
-- Generating done
make: 'plugin.opt.so' is up to date.
-- Build files have been written to: /home/appo/openxr-simple-example/build
make: Leaving directory '/home/appo/ILLIXR/timewarp_gl'
make[2]: Entering directory '/home/appo/ILLIXR/open_vins/build/Release'
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 
make: Entering directory '/home/appo/openxr-simple-example/build'
make[3]: Entering directory '/home/appo/ILLIXR/open_vins/build/Release'
CMake Warning at CMakeLists.txt:32 (find_package):
  By not providing "Findrealsense2.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "realsense2", but CMake did not find one.

  Could not find a package configuration file provided by "realsense2" with
  any of the following names:

    realsense2Config.cmake
    realsense2-config.cmake

  Add the installation prefix of "realsense2" to CMAKE_PREFIX_PATH or set
  "realsense2_DIR" to a directory containing one of the above files.  If
  "realsense2" provides a separate development package or SDK, be sure it has
  been installed.


make[1]: Entering directory '/home/appo/openxr-simple-example/build'
make[3]: Leaving directory '/home/appo/ILLIXR/open_vins/build/Release'
make[2]: Entering directory '/home/appo/openxr-simple-example/build'
make[2]: Leaving directory '/home/appo/openxr-simple-example/build'
-- Checking for module 'libuvc'
[100%] Built target openxr-example
make[1]: Leaving directory '/home/appo/openxr-simple-example/build'
--   No package 'libuvc' found
make: Leaving directory '/home/appo/openxr-simple-example/build'
-- Checking for module 'libavcodec'
--   No package 'libavcodec' found
[ 44%] Built target ov_core_lib
make[3]: Entering directory '/home/appo/ILLIXR/open_vins/build/Release'
make[3]: Leaving directory '/home/appo/ILLIXR/open_vins/build/Release'
make[3]: Entering directory '/home/appo/ILLIXR/open_vins/build/Release'
[ 51%] Built target test_webcam
make[3]: Leaving directory '/home/appo/ILLIXR/open_vins/build/Release'
[ 85%] Built target ov_msckf_lib
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (UDEV) does
  not match the name of the calling package (udev).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Findudev.cmake:63 (find_package_handle_standard_args)
  CMakeLists.txt:50 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

make[3]: Entering directory '/home/appo/ILLIXR/open_vins/build/Release'
-- Checking for one of the modules 'wayland-protocols'
make[3]: Entering directory '/home/appo/ILLIXR/open_vins/build/Release'
make[3]: Leaving directory '/home/appo/ILLIXR/open_vins/build/Release'
make[3]: Leaving directory '/home/appo/ILLIXR/open_vins/build/Release'
[ 92%] Built target slam2
-- Enabled drivers: dummy hdk hydra illixr v4l2
[100%] Built target run_simulation
make[2]: Leaving directory '/home/appo/ILLIXR/open_vins/build/Release'
make[1]: Leaving directory '/home/appo/ILLIXR/open_vins/build/Release'
make: Leaving directory '/home/appo/ILLIXR/open_vins'
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/appo/monado_integration/build
make: Entering directory '/home/appo/monado_integration/build'
make[1]: Entering directory '/home/appo/monado_integration/build'
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
[  4%] Built target aux_math
[ 13%] Built target aux_tracking
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
[ 14%] Built target aux_os
make[2]: Entering directory '/home/appo/monado_integration/build'
[ 28%] Built target aux_util
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
[ 29%] Built target aux_ogl
[ 29%] Built target drv_v4l2
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
[ 32%] Built target drv_hydra
[ 32%] Built target drv_hdk
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
[ 35%] Built target drv_dummy
[ 36%] Built target drv_illixr
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
[ 57%] Built target comp
[ 68%] Built target st_gui
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
[ 73%] Built target st_prober
make[2]: Entering directory '/home/appo/monado_integration/build'
[ 96%] Built target st_oxr
make[2]: Leaving directory '/home/appo/monado_integration/build'
[ 97%] Built target target_lists
make[2]: Entering directory '/home/appo/monado_integration/build'
make[2]: Leaving directory '/home/appo/monado_integration/build'
[100%] Built target openxr_monado
make[1]: Leaving directory '/home/appo/monado_integration/build'
make: Leaving directory '/home/appo/monado_integration/build'
Runtime supports 7 extensions
	XR_EXT_debug_utils v3
	XR_KHR_convert_timespec_time v1
	XR_KHR_opengl_enable v7
	XR_KHR_opengl_es_enable v6
	XR_KHR_vulkan_enable v6
	XR_MND_egl_enable v1
	XR_MND_headless v1
Runtime supports extensions:
	XR_KHR_opengl_enable: 1
	XR_EXT_hand_tracking: 0
	XR_KHR_composition_layer_cylinder: 0
	XR_KHR_composition_layer_depth: 0
Runtime Name: Monado(XRT) by Collabora et al
Runtime Version: 0.1.42
Successfully got XrSystem with id 1 for HMD form factor
System properties for system 1: "Monado: Illixr", vendor ID 42
	Max layers          : 1
	Max swapchain height: 16384
	Max swapchain width : 16384
	Orientation Tracking: 1
	Position Tracking   : 0
Runtime supports 1 view configurations
Runtime supports view configurations:
2: FOV mutable: 0
View Configuration View 0:
	Resolution       : Recommended 1024x1024, Max: 2048x2048
	Swapchain Samples: Recommended: 1, Max: 1)
View Configuration View 1:
	Resolution       : Recommended 1024x1024, Max: 2048x2048
	Swapchain Samples: Recommended: 1, Max: 1)
We want OpenGL 3.3.0, but runtime only supports OpenGL 4.5.0 - 4.6.1023!
Using OpenGL version: 4.6 (Core Profile) Mesa 20.0.8
Using OpenGL Renderer: Mesa Intel(R) HD Graphics 520 (SKL GT2)
Successfully compiled vertex shader!
Successfully compiled fragment shader!
Successfully linked shader program!
comp_window_direct_init_randr - No non-desktop output available.
client_gl_compositor_init - Needed extension GL_EXT_memory_object_fd not supported
XR_ERROR_INITIALIZATION_FAILED in xrCreateSession:  failed create a compositor
Failed to create session [XR_ERROR_INITIALIZATION_FAILED]
Traceback (most recent call last):
  File "runner/main.py", line 316, in <module>
    main()
  File "/home/appo/miniconda3/envs/illixr-runner/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/appo/miniconda3/envs/illixr-runner/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/appo/miniconda3/envs/illixr-runner/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/appo/miniconda3/envs/illixr-runner/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "runner/main.py", line 314, in main
    asyncio.run(run_config(Path(config_path)))
  File "/home/appo/miniconda3/envs/illixr-runner/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/appo/miniconda3/envs/illixr-runner/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "runner/main.py", line 306, in run_config
    await loaders[loader](config)
  File "runner/main.py", line 265, in load_monado
    await subprocess_run(
  File "runner/main.py", line 101, in subprocess_run
    raise subprocess.CalledProcessError(return_code, cmd=shlex.join(args))
subprocess.CalledProcessError: Command '/home/appo/openxr-simple-example/build/openxr-example' returned non-zero exit status 1.
```

**Comment by Zee2** [comment]
Ah, I see the problem.

Your system does not support GL_EXT_memory_object_fd. This is required for Monado. 

What GPU are you using?

**Comment by YQGong** [comment]
I use my laptop without an external video card.

`lspci | grep -i vga` returned:
`Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)`

So, does monado require a high-end video card?

**Comment by Zee2** [comment]
Ah. Yes, Monado requires a discrete GPU. Intel integrated graphics will not work for Monado.

Intel integrated graphics _may_ work with the standalone ILLIXR system (of course, without the CUDA components...), but it is not supported, and we will probably not be able to help you with integrated graphics-specific issues.

**Comment by apache8080** [comment]
If you continue to run into issues with running ILLIXR on your machine, follow [these instructions](https://github.com/ILLIXR/ILLIXR/blob/master/qemu/INSTRUCTIONS.md) on using ILLIXR QEMU. We have tested this and it seems to be stable. You probably won’t be able to run Monado in QEMU but you will be able to run gldemo.

**Comment by mhuzai** [comment]
You can check whether you have `GL_EXT_memory_object_fd` by doing: `glxinfo | grep GL_EXT_memory_object_fd`

As the others mentioned, standalone ILLIXR should run on your machine. If it doesn't, try out the Qemu instructions linked above.
