### ISSUE TITLE
AWS ILLIXR- Failed to retrieve a framebuffer config

### ISSUE THREAD

**Issue by pcg108** [ILLIXR/ILLIXR#386]
Hi, I am trying to run ILLIXR on an AWS EC2 P2 instance. The installation was successful, but when I run ILLIXR I get the following error. I am connected to the instance using X11 forwarding with X2Go. I also got the same error when using VNC Viewer. 

Is this somehow related to how I am connecting to the instance? I had a hunch that perhaps it is due to the fact that there is no inherent display connected to the device since it is a EC2 instance. Any help would be greatly appreciated.

```
ubuntu@ip-172-31-89-193:~/ILLIXR$ ./runner.sh configs/native.yaml
DETECT [dep <- 'miniconda3', dir <- '/opt/ILLIXR/miniconda3']
(0, PosixPath('offline_imu/plugin.opt.so'))                                     
(9, PosixPath('timewarp_gl/plugin.opt.so'))                                     
(4, PosixPath('pose_prediction/plugin.opt.so'))                                 
(1, PosixPath('offline_cam/plugin.opt.so'))                                     
(5, PosixPath('ground_truth_slam/plugin.opt.so'))                               
(8, PosixPath('offload_data/plugin.opt.so'))                                    
(7, PosixPath('debugview/plugin.opt.so'))                                       
(6, PosixPath('gldemo/plugin.opt.so'))                                          
(10, PosixPath('.cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/plugin.opt.so'))
(3, PosixPath('gtsam_integrator/plugin.opt.so'))                                
(2, PosixPath('.cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/plugin.opt.so'))
100%|██████████████████████████████████████| 11/11 [00:01<00:00,  7.06plugins/s]
** ERROR ** Failed to retrieve a framebuffer config
Traceback (most recent call last):
  File "runner/runner/main.py", line 404, in <module>
    main()
  File "/opt/ILLIXR/miniconda3/envs/illixr-runner/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/ILLIXR/miniconda3/envs/illixr-runner/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/ILLIXR/miniconda3/envs/illixr-runner/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/ILLIXR/miniconda3/envs/illixr-runner/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "runner/runner/main.py", line 402, in main
    run_config(Path(config_path))
  File "runner/runner/main.py", line 394, in run_config
    actions[action](config)
  File "runner/runner/main.py", line 152, in load_native
    subprocess_run(
  File "/home/ubuntu/ILLIXR/runner/runner/util.py", line 171, in subprocess_run
    raise CalledProcessError(
util.CalledProcessError: Command returned non-zero exit status 1
command: env 'ILLIXR_DATA=.cache/paths/http%%c%%s%%srobotics.ethz.ch%%s~asl-datasets%%sijrr_euroc_mav_dataset%%svicon_room1%%sV1_02_medium%%sV1_02_medium.zip/mav0' ILLIXR_DEMO_DATA=demo_data ILLIXR_OFFLOAD_ENABLE=False ILLIXR_ALIGNMENT_ENABLE=False ILLIXR_ENABLE_VERBOSE_ERRORS=False ILLIXR_RUN_DURATION=60 ILLIXR_ENABLE_PRE_SLEEP=False KIMERA_ROOT=.cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/ AUDIO_ROOT=.cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/ REALSENSE_CAM=auto __GL_MaxFramesAllowed=1 __GL_SYNC_TO_VBLANK=1 runtime/main.opt.exe offline_imu/plugin.opt.so offline_cam/plugin.opt.so .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/plugin.opt.so gtsam_integrator/plugin.opt.so pose_prediction/plugin.opt.so ground_truth_slam/plugin.opt.so gldemo/plugin.opt.so debugview/plugin.opt.so offload_data/plugin.opt.so timewarp_gl/plugin.opt.so .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/plugin.opt.so
```

**Comment by charmoniumQ** [comment]
Comes from [this line](https://github.com/ILLIXR/ILLIXR/blob/e17e6c5679822a4f021d0a6f85628b5ab698b384/common/extended_window.hpp#L84).
Can you run other OpenGL applications without error on your EC2 instance?

**Comment by pcg108** [comment]
When i try to run ```glmark2``` I get:

```
ubuntu@ip-172-31-89-193:~$ glmark2
Error: main: Could not initialize canvas
```

So perhaps there is a problem with running OpenGL with X11 from EC2?

**Comment by charmoniumQ** [comment]
It would seem so.

**Comment by astro-friedel** [comment]
This issue appears to be completed
