### ISSUE TITLE
riscv64 runtime issue

### ISSUE THREAD

**Issue by pcg108** [ILLIXR/ILLIXR#390]
Hello,

I am trying to compile and run ILLIXR in Ubuntu 20.04 on a riscv64 architecture in Qemu. I managed to compile all the dependencies successfully, but when I run ILLIXR I get the following runtime error:

```
ubuntu@ubuntu:~/ILLIXR$ ./runner.sh configs/headless.yaml
*Warning* Installation log for conda not found at '.cache/deps/miniconda3.sh'.
Checking in '/opt/ILLIXR/miniconda3'.
./runner.sh: line 43: /opt/ILLIXR/miniconda3/etc/profile.d/conda.sh: No such file or directory
*Warning* Conda not found. Attempting to run ILLIXR via 'python' anyway ...
(0, PosixPath('offline_imu/plugin.opt.so'))
(4, PosixPath('pose_prediction/plugin.opt.so'))
(5, PosixPath('ground_truth_slam/plugin.opt.so'))
(1, PosixPath('offline_cam/plugin.opt.so'))
(6, PosixPath('gldemo/plugin.opt.so'))
(7, PosixPath('timewarp_gl/plugin.opt.so'))
(3, PosixPath('gtsam_integrator/plugin.opt.so'))
(8, PosixPath('.cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/plugin.opt.so'))
(2, PosixPath('.cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/plugin.opt.so'))
100%|████████████████████████████████████████| 9/9 [00:11<00:00,  1.23s/plugins]
thread,thread,271002321328270993928624thread,270851371440,opencv threadpool worker,,opencv threadpool worker,02,opencv threadpool worker,1


WARNING: Logging before InitGoogleLogging() is written to STDERR
I0704 00:37:08.554834  1066 RegularVioBackEnd.cpp:114] Using Regular VIO backend.
I0704 00:37:08.567873  1066 Pipeline.cpp:474] Pipeline Modules running in sequential mode (parallel_run set to 0).
topic buffer createdGetting second/third order dodecahedron
Getting second/third order dodecahedron
thread,270798918064,threadloop,offline_imu
thread,270046065072,threadloop,offline_cam
thread,270817800624,sqlite thread,plugin_name
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
WARNING: This target JIT is not designed for the host you are running.  If bad things happen, please choose a different -march switch.
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
LLVM ERROR: Cannot select: 0x1e037830: ch = store<(store 4 into %ir.sample_mask_ptr15, align 16), trunc to i32> 0x1e012548:1, 0x1e0330d0, 0x1dfede88, undef:i64
  0x1e0330d0: i64 = RISCVISD::SELECT_CC 0x1e01e1d0, Constant:i64<0>, Constant:i64<22>, 0x1e033208, Constant:i64<0>
    0x1e01e1d0: i64 = and 0x1dff0fa0, Constant:i64<1>
      0x1dff0fa0: i64 = srl 0x1dfcab20, Constant:i64<58>
        0x1dfcab20: i64,ch = load<(load 8 from %fixed-stack.5)> 0x1de1bd28, FrameIndex:i64<-2>, undef:i64
          0x1dfcaab8: i64 = FrameIndex<-2>
          0x1dfca9e8: i64 = undef
        0x1dfedef0: i64 = Constant<58>
      0x1dfcd5e8: i64 = Constant<1>
    0x1dfcd518: i64 = Constant<0>
    0x1e008ee0: i64 = Constant<22>
    0x1e033208: i64 = sra 0x1e0331a0, Constant:i64<31>
      0x1e0331a0: i64 = sign_extend_inreg 0x1e033138, ValueType:ch:i32
        0x1e033138: i64 = shl 0x1e012548, Constant:i64<28>
          0x1e012548: i64,ch = load<(load 4 from %ir.36), zext from i32> 0x1e022210, 0x1dfd12b0, undef:i64
            0x1dfd12b0: i64 = add 0x1dfca368, Constant:i64<31272>
              0x1dfca368: i64,ch = CopyFromReg 0x1de1bd28, Register:i64 %27
                0x1dfca300: i64 = Register %27
              0x1dfd1248: i64 = Constant<31272>
                          0x1dfca9e8: i64 = undef
                        0x1dfd5f68: i64 = Constant<28>
                    0x1dfd3a00: i64 = Constant<31>
                  0x1dfcd518: i64 = Constant<0>
                0x1dfede88: i64 = add nuw FrameIndex:i64<6>, Constant:i64<240>
                  0x1dfcd310: i64 = FrameIndex<6>
                  0x1dfede20: i64 = Constant<240>
                0x1dfca9e8: i64 = undef
              In function: fs_variant_partial
              Aborted (core dumped)   
              Traceback (most recent call last):
                File "runner/runner/main.py", line 404, in <module>
                  main()
                File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
                  return self.main(*args, **kwargs)
                File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
                  rv = self.invoke(ctx)
                File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
                  return ctx.invoke(self.callback, **ctx.params)
                File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
                  return callback(*args, **kwargs)
                File "runner/runner/main.py", line 402, in main
                  run_config(Path(config_path))
                File "runner/runner/main.py", line 394, in run_config
                  actions[action](config)
                File "runner/runner/main.py", line 152, in load_native
                  subprocess_run(
                File "/home/ubuntu/ILLIXR/runner/runner/util.py", line 171, in subprocess_run
                  raise CalledProcessError(
              util.CalledProcessError: Command returned non-zero exit status 134
              command: env 'ILLIXR_DATA=.cache/paths/http%%c%%s%%srobotics.ethz.ch%%s~asl-datasets%%sijrr_euroc_mav_dataset%%svicon_room1%%sV1_02_medium%%sV1_02_medium.zip/mav0' ILLIXR_DEMO_DATA=demo_data ILLIXR_OFFLOAD_ENABLE=False ILLIXR_ALIGNMENT_ENABLE=False ILLIXR_ENABLE_VERBOSE_ERRORS=False ILLIXR_RUN_DURATION=60 ILLIXR_ENABLE_PRE_SLEEP=False KIMERA_ROOT=.cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/ AUDIO_ROOT=.cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/ REALSENSE_CAM=auto __GL_MaxFramesAllowed=1 __GL_SYNC_TO_VBLANK=1 xvfb-run runtime/main.opt.exe offline_imu/plugin.opt.so offline_cam/plugin.opt.so .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/plugin.opt.so gtsam_integrator/plugin.opt.so pose_prediction/plugin.opt.so ground_truth_slam/plugin.opt.so gldemo/plugin.opt.so timewarp_gl/plugin.opt.so .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/plugin.opt.so
```

Which library is this error referring to? Looks to me like some configuration is not working with riscv. Any help would be really appreciated!

**Comment by charmoniumQ** [comment]
Try modifying the `config/headless.yaml` to look more like `config/debug.yaml` (while keeping it headless). This will drop you into a GDB from which you can type `run` to debug your error.

**Comment by pcg108** [comment]
In the current main branch of ILLIXR I don't see ``debug.yaml`` under ``configs/``. Can you share which branch I can find it under?

**Comment by pcg108** [comment]
I added the GDB command to headless.yaml. It looks like it looks for an X server even though it is being run with headless.yaml. Is that correct, or an issue when running in GDB?

```
ubuntu@ubuntu:~/ILLIXR$ ./runner.sh configs/headless.yaml
*Warning* Installation log for conda not found at '.cache/deps/miniconda3.sh'.
Checking in '/opt/ILLIXR/miniconda3'.
./runner.sh: line 43: /opt/ILLIXR/miniconda3/etc/profile.d/conda.sh: No such file or directory
*Warning* Conda not found. Attempting to run ILLIXR via 'python' anyway ...
(0, PosixPath('offline_imu/plugin.opt.so'))
(5, PosixPath('ground_truth_slam/plugin.opt.so'))
(4, PosixPath('pose_prediction/plugin.opt.so'))
(1, PosixPath('offline_cam/plugin.opt.so'))
(6, PosixPath('gldemo/plugin.opt.so'))                                          
(7, PosixPath('timewarp_gl/plugin.opt.so'))                                     
(3, PosixPath('gtsam_integrator/plugin.opt.so'))                                
(8, PosixPath('.cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/plugin.opt.so'))
(2, PosixPath('.cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/plugin.opt.so'))
100%|████████████████████████████████████████| 9/9 [00:10<00:00,  1.13s/plugins]
Reading symbols from runtime/main.opt.exe...
(gdb) step
The program is not being run.
(gdb) s
The program is not being run.
(gdb) run
Starting program: /home/ubuntu/ILLIXR/runtime/main.opt.exe offline_imu/plugin.opt.so offline_cam/plugin.opt.so .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/plugin.opt.so gtsam_integrator/plugin.opt.so pose_prediction/plugin.opt.so ground_truth_slam/plugin.opt.so gldemo/plugin.opt.so timewarp_gl/plugin.opt.so .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/plugin.opt.so
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/riscv64-linux-gnu/libthread_db.so.1".
** ERROR ** Cannot connect to X server
[Inferior 1 (process 1506) exited with code 01]

```

**Comment by pcg108** [comment]
Thanks, 

I installed xrdp to connect to my remote instance running the Qemu riscv64 emulator, and enabled a display view (instead of headless). With that I was able to run ```glxgears``` and ```configs/native.yaml```.
